-- Add role and status columns to users
ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user';
ALTER TABLE users ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';

-- Create banned_ips table
CREATE TABLE IF NOT EXISTS banned_ips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip TEXT NOT NULL UNIQUE,
    reason TEXT,
    banned_by UUID,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create admin_logs table
CREATE TABLE IF NOT EXISTS admin_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    user_id UUID,
    admin_id UUID,
    target_user_id UUID,
    target_ip TEXT,
    username TEXT,
    ip TEXT,
    changes TEXT,
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Disable RLS
ALTER TABLE banned_ips DISABLE ROW LEVEL SECURITY;
ALTER TABLE admin_logs DISABLE ROW LEVEL SECURITY;
