# Supabase configuration
# Add these to your .env file:
# SUPABASE_URL=https://your-project.supabase.co
# SUPABASE_KEY=your-anon-key

import os
from supabase import create_client, Client

def get_supabase_client() -> Client:
    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_KEY")
    
    if not url or not key:
        raise ValueError("SUPABASE_URL and SUPABASE_KEY must be set")
    
    return create_client(url, key)

def init_supabase_tables():
    """Initialize tables in Supabase. Run this once to create tables."""
    client = get_supabase_client()
    
    # Users table (will use Supabase Auth, but we keep a profile table)
    client.table("users").execute()
    
    # Create tables using SQL
    tables_sql = """
    -- Users profile table (links to Supabase Auth)
    CREATE TABLE IF NOT EXISTS users (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        username TEXT UNIQUE NOT NULL,
        email TEXT UNIQUE NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );

    -- Folders for todo app
    CREATE TABLE IF NOT EXISTS folders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID NOT NULL,
        name TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );

    -- Todos
    CREATE TABLE IF NOT EXISTS todos (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID NOT NULL,
        folder_id BIGINT,
        title TEXT,
        priority TEXT,
        due_date TEXT,
        due_time TEXT DEFAULT '23:59',
        completed INTEGER DEFAULT 0,
        reminder_sent INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY (folder_id) REFERENCES folders(id) ON DELETE SET NULL
    );

    -- Notebooks
    CREATE TABLE IF NOT EXISTS notebooks (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID NOT NULL,
        name TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );

    -- Notes
    CREATE TABLE IF NOT EXISTS notes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID NOT NULL,
        notebook_id BIGINT NOT NULL,
        section TEXT NOT NULL DEFAULT 'General',
        title TEXT NOT NULL,
        content TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW(),
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY (notebook_id) REFERENCES notebooks(id) ON DELETE CASCADE
    );

    -- File folders
    CREATE TABLE IF NOT EXISTS file_folders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID NOT NULL,
        name TEXT NOT NULL,
        parent_id BIGINT,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY (parent_id) REFERENCES file_folders(id) ON DELETE CASCADE
    );

    -- Files
    CREATE TABLE IF NOT EXISTS files (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID NOT NULL,
        name TEXT NOT NULL,
        type TEXT NOT NULL,
        mime_type TEXT,
        size BIGINT DEFAULT 0,
        data TEXT,
        folder_id BIGINT,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        modified_at TIMESTAMPTZ DEFAULT NOW(),
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY (folder_id) REFERENCES file_folders(id) ON DELETE SET NULL
    );
    """
    
    # Execute raw SQL
    client.postgrest.schema = "public"
    print("Tables should be created in Supabase dashboard via SQL editor")
    return client
